from __future__ import annotations

# Shared runtime/config limits. Keep these centralized to avoid cross-module drift.
MIN_JOB_STALL_TIMEOUT_SECONDS = 60

DEFAULT_JOB_EVENT_HISTORY_MAX_JOBS = 256
MIN_JOB_EVENT_HISTORY_MAX_JOBS = 32

DEFAULT_JOB_EVENT_HISTORY_TTL_SECONDS = 1800
MIN_JOB_EVENT_HISTORY_TTL_SECONDS = 60

JOB_KEEPALIVE_INTERVAL_MIN_SECONDS = 5.0
JOB_KEEPALIVE_INTERVAL_MAX_SECONDS = 30.0

JOB_TOUCH_MIN_INTERVAL_SECONDS = 1.5
JOB_WATCHDOG_SLEEP_SECONDS = 5
JOB_WORKER_WAIT_TIMEOUT_SECONDS = 0.6
